import type { Noticia } from '@/types';

// Imagens genéricas do Unsplash para o mock inicial.
const IMG = {
  cidade: 'https://images.unsplash.com/photo-1523731407965-2430cd12f5e4?w=1600&q=80',
  obras: 'https://images.unsplash.com/photo-1590496793929-36417d3117de?w=1600&q=80',
  policia: 'https://images.unsplash.com/photo-1605745341112-85968b19335b?w=1600&q=80',
  transito: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=1600&q=80',
  agro: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=1600&q=80',
  soja: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=1600&q=80',
  gado: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=1600&q=80',
  festa: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6a3?w=1600&q=80',
  esporte: 'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=1600&q=80',
  cultura: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600&q=80',
};

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

export const NOTICIAS_MOCK: Noticia[] = [
  {
    _id: 'mock-1',
    titulo: 'Prefeitura de Santa Carmem anuncia pacote de R$ 4,2 milhões em obras de pavimentação',
    subtitulo: 'Investimento contempla 8 bairros e deve beneficiar mais de 3 mil moradores até o fim do ano',
    slug: 'prefeitura-santa-carmem-pacote-pavimentacao-2026',
    categoria: 'cidade',
    categoriaNome: 'Cidade',
    imagemUrl: IMG.obras,
    resumo: 'O prefeito apresentou nesta segunda-feira o maior pacote de infraestrutura urbana dos últimos cinco anos, com recursos próprios e convênios estaduais.',
    publicadoEm: daysAgo(0),
    destaque: true,
    autor: { _id: 'a1', nome: 'Redação', slug: 'redacao' },
    tags: ['prefeitura', 'obras', 'pavimentação'],
  },
  {
    _id: 'mock-2',
    titulo: 'Safra de soja em Santa Carmem supera expectativas e produtores comemoram produtividade recorde',
    subtitulo: 'Colheita registra 65 sacas por hectare, a maior média da microrregião',
    slug: 'safra-soja-santa-carmem-recorde-2026',
    categoria: 'agronegocio',
    categoriaNome: 'Agronegócio',
    imagemUrl: IMG.soja,
    resumo: 'Clima favorável, manejo técnico aprimorado e investimento em sementes de alta tecnologia impulsionaram os resultados desta safra.',
    publicadoEm: daysAgo(1),
    destaque: true,
    autor: { _id: 'a1', nome: 'Redação', slug: 'redacao' },
    tags: ['soja', 'safra', 'agronegócio'],
  },
  {
    _id: 'mock-3',
    titulo: 'Polícia Militar apreende veículo com carga irregular na BR-163',
    subtitulo: 'Ação conjunta com a PRF flagrou transporte sem nota fiscal em operação de rotina',
    slug: 'pm-apreende-carga-br-163',
    categoria: 'policia',
    categoriaNome: 'Polícia',
    imagemUrl: IMG.policia,
    resumo: 'A operação ocorreu na manhã desta terça-feira no km 380 da rodovia, próximo ao trevo de Santa Carmem.',
    publicadoEm: daysAgo(1),
    autor: { _id: 'a1', nome: 'Redação', slug: 'redacao' },
    tags: ['polícia', 'PM', 'BR-163'],
  },
  {
    _id: 'mock-4',
    titulo: 'Festa do Trabalhador Rural reúne mais de 5 mil pessoas no parque de exposições',
    subtitulo: 'Evento contou com shows, leilão beneficente e praça de alimentação com comida típica',
    slug: 'festa-trabalhador-rural-2026',
    categoria: 'eventos',
    categoriaNome: 'Esportes & Eventos',
    imagemUrl: IMG.festa,
    resumo: 'A tradicional festa, em sua 28ª edição, é um dos maiores eventos do calendário cultural de Santa Carmem.',
    publicadoEm: daysAgo(2),
    destaque: true,
    autor: { _id: 'a1', nome: 'Redação', slug: 'redacao' },
    tags: ['cultura', 'festa', 'trabalhador rural'],
  },
  {
    _id: 'mock-5',
    titulo: 'Câmara Municipal aprova projeto que cria programa de incentivo à agricultura familiar',
    subtitulo: 'Proposta prevê linha de crédito facilitada e compra direta de alimentos para escolas',
    slug: 'camara-incentivo-agricultura-familiar',
    categoria: 'cidade',
    categoriaNome: 'Cidade',
    imagemUrl: IMG.cidade,
    resumo: 'O projeto, de autoria do Executivo, foi aprovado por unanimidade em sessão realizada na última sexta-feira.',
    publicadoEm: daysAgo(3),
    autor: { _id: 'a1', nome: 'Redação', slug: 'redacao' },
    tags: ['câmara', 'agricultura familiar'],
  },
  {
    _id: 'mock-6',
    titulo: 'Gado nelore de Santa Carmem é destaque em leilão regional com lances acima da média',
    subtitulo: 'Criadores locais apresentaram 120 animais em evento que movimentou R$ 2,8 milhões',
    slug: 'nelore-santa-carmem-leilao-regional',
    categoria: 'agronegocio',
    categoriaNome: 'Agronegócio',
    imagemUrl: IMG.gado,
    resumo: 'A qualidade genética dos animais da região vem chamando atenção de compradores de todo o Centro-Oeste.',
    publicadoEm: daysAgo(3),
    autor: { _id: 'a1', nome: 'Redação', slug: 'redacao' },
    tags: ['pecuária', 'nelore', 'leilão'],
  },
  {
    _id: 'mock-7',
    titulo: 'Campeonato municipal de futebol abre inscrições para a temporada 2026',
    subtitulo: 'Vinte equipes já confirmaram participação; torneio começa no dia 15 de maio',
    slug: 'campeonato-municipal-futebol-2026',
    categoria: 'eventos',
    categoriaNome: 'Esportes & Eventos',
    imagemUrl: IMG.esporte,
    resumo: 'A Secretaria de Esportes garantiu premiação em dinheiro para as três primeiras colocadas, além de troféus.',
    publicadoEm: daysAgo(4),
    autor: { _id: 'a1', nome: 'Redação', slug: 'redacao' },
    tags: ['futebol', 'campeonato'],
  },
  {
    _id: 'mock-8',
    titulo: 'Trânsito na região central passará por mudanças a partir da próxima semana',
    subtitulo: 'Duas ruas se tornarão mão única e haverá reforço na sinalização',
    slug: 'transito-centro-mudancas',
    categoria: 'policia',
    categoriaNome: 'Polícia',
    imagemUrl: IMG.transito,
    resumo: 'As alterações visam reduzir congestionamentos nos horários de pico e melhorar a fluidez do trânsito.',
    publicadoEm: daysAgo(5),
    autor: { _id: 'a1', nome: 'Redação', slug: 'redacao' },
    tags: ['trânsito', 'centro'],
  },
  {
    _id: 'mock-9',
    titulo: 'Produtores da região se preparam para a próxima safra com foco em sustentabilidade',
    subtitulo: 'Práticas de plantio direto e rotação de culturas ganham cada vez mais adeptos',
    slug: 'produtores-safra-sustentabilidade',
    categoria: 'agronegocio',
    categoriaNome: 'Agronegócio',
    imagemUrl: IMG.agro,
    resumo: 'Cooperativas locais oferecem capacitação gratuita e incentivos para quem adota técnicas de manejo conservacionista.',
    publicadoEm: daysAgo(6),
    autor: { _id: 'a1', nome: 'Redação', slug: 'redacao' },
    tags: ['sustentabilidade', 'safra'],
  },
  {
    _id: 'mock-10',
    titulo: 'Exposição de arte local leva público ao Centro Cultural neste fim de semana',
    subtitulo: 'Mostra reúne 15 artistas da cidade e da região com entrada gratuita',
    slug: 'exposicao-arte-centro-cultural',
    categoria: 'eventos',
    categoriaNome: 'Esportes & Eventos',
    imagemUrl: IMG.cultura,
    resumo: 'A curadoria privilegiou obras que dialogam com a identidade mato-grossense e o cotidiano do homem do campo.',
    publicadoEm: daysAgo(7),
    autor: { _id: 'a1', nome: 'Redação', slug: 'redacao' },
    tags: ['cultura', 'arte', 'exposição'],
  },
];
